name: Build and Release

on:
  push:
    tags: ['v*', 'test*']

jobs:
  build-zip:
    name: Build and Publish Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install
        run: |
          go mod download
          cd web && npm install
      - name: Build
        run: make
      - name: LS
        run:  ls -la bin

      - name: Archive Release # 打包文件为 zip
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ginvue-${{ github.ref }}.zip
          path: 'bin'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # 因为之前已经创建了 Release，所以要进行更新
          omitName: true # 更新的时候不改变 Release 的名字
          artifacts: ginvue-${{ github.ref }}.zip # 多个文件逗号分开
          token: ${{ secrets.GITHUB_TOKEN }}
