name: Build and Release

on:
  release: # 发布 Release 后才会运行
    types: [published]

jobs:
  build-zip:
    name: Build and Publish Extension Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build 
        run: |
         go mod download
         cd web && npm install
         make

      - name: Archive Release V3 # 打包文件为 zip
        uses: thedoctor0/zip-release@master
        with:
          filename: ginvue-${{ github.ref }}.zip
          path: 'bin/*'

      - name: Upload Release 
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # 因为之前已经创建了 Release，所以要进行更新
          omitName: true # 更新的时候不改变 Release 的名字
          artifacts: ginvue-${{ github.ref }}.zip # 多个文件逗号分开
          token: ${{ secrets.GITHUB_TOKEN }}
